package com.arthix.backend.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "transfers", indexes = {
    @Index(name = "idx_transfers_due", columnList = "status, scheduled_at"),
    @Index(name = "idx_transfers_sender", columnList = "sender_id, created_at")
})
public class Transfer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "recipient_id", nullable = false)
    private User recipient;

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    @Column(length = 140)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 12)
    private TransferStatus status = TransferStatus.PENDING;

    @Enumerated(EnumType.STRING)
    @Column(name = "transfer_type", nullable = false, length = 12)
    private TransferType transferType;

    @Column(name = "scheduled_at", nullable = false)
    private Instant scheduledAt;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "executed_at")
    private Instant executedAt;

    @Column(name = "failure_reason", length = 200)
    private String failureReason;

    @Column(name = "receipt_no", length = 24)
    private String receiptNo;

    /** Set when this transfer is one occurrence generated by a recurring plan. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recurring_transfer_id")
    private RecurringTransfer recurringTransfer;

    protected Transfer() {}

    public Transfer(User sender, User recipient, BigDecimal amount, String description,
                    TransferType transferType, Instant scheduledAt, RecurringTransfer recurringTransfer) {
        this.sender = sender;
        this.recipient = recipient;
        this.amount = amount;
        this.description = description;
        this.transferType = transferType;
        this.scheduledAt = scheduledAt;
        this.recurringTransfer = recurringTransfer;
    }

    public Long getId() { return id; }
    public User getSender() { return sender; }
    public User getRecipient() { return recipient; }
    public BigDecimal getAmount() { return amount; }
    public String getDescription() { return description; }
    public TransferStatus getStatus() { return status; }
    public void setStatus(TransferStatus status) { this.status = status; }
    public TransferType getTransferType() { return transferType; }
    public Instant getScheduledAt() { return scheduledAt; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getExecutedAt() { return executedAt; }
    public void setExecutedAt(Instant executedAt) { this.executedAt = executedAt; }
    public String getFailureReason() { return failureReason; }
    public void setFailureReason(String failureReason) { this.failureReason = failureReason; }
    public String getReceiptNo() { return receiptNo; }
    public void setReceiptNo(String receiptNo) { this.receiptNo = receiptNo; }
    public RecurringTransfer getRecurringTransfer() { return recurringTransfer; }
}