spring.application.name=arthix-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:8080/arthix_bank
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:elamraouimohamed010203@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# bach frontend ychouf message dyal error
server.error.include-message=always

logging.level.org.springframework.security=DEBUG

app.jwt.secret=ZmFrZS1zZWNyZXQtZm9yLWRldi1vbmx5LWNoYW5nZS1tZS0xMjM0NTY3ODkw
app.jwt.expiration-ms=86400000